// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uptxtdgzxlberkzqwlnn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVwdHh0ZGd6eGxiZXJrenF3bG5uIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY0MjcwNDAsImV4cCI6MjA3MjAwMzA0MH0.Q0d7mpgCva3yE_JaImirYscz__bJnRrhdAmtq_x4w8M";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});